name = "gold-rate-tanishq-worker"
main = "index.js"
compatibility_date = "2024-11-01"

[triggers]
crons = ["30 */3 * * *"]

[vars]
GITHUB_OWNER = "gaurav-gandhi-2411"
GITHUB_REPO = "gold-rate-tracker"
